
-- Create a database

CREATE DATABASE IF NOT EXISTS SAMPLE_ASSET_MANAGEMENT;

USE SAMPLE_ASSET_MANAGEMENT;

CREATE TABLE IF NOT EXISTS CUSTOMERS (
	ID VARCHAR(10) PRIMARY KEY,
    NAME VARCHAR(70),
    SEGMENT CHAR(20),
    TYPE CHAR(20),
    ADVISOR VARCHAR(75),
    TEAM_HEAD VARCHAR(75),
    SEGMENT_HEAD VARCHAR(75),
    REGION VARCHAR(30)
);

CREATE TABLE IF NOT EXISTS INVESTMENT (
	ISIN VARCHAR(12) PRIMARY KEY,
    SECURITY_NAME VARCHAR(50),
    SECURITY_REGION VARCHAR(30),
    ASSET_TYPE VARCHAR(20),
    SUB_ASSET_TYPE VARCHAR(50),
    CCY_CODE CHAR(3)
);

CREATE TABLE IF NOT EXISTS EXCH_RATE (
	FROM_CCY CHAR(3) NOT NULL,
    TO_CCY CHAR(3) NOT NULL,
    RATE NUMERIC
);

CREATE TABLE IF NOT EXISTS HOLDINGS (
	MONTH CHAR(3),
	ID VARCHAR(10),
	ISIN VARCHAR(12),
    CCY_CODE CHAR(3),
	AMOUNT NUMERIC,
    FOREIGN KEY (ID) REFERENCES CUSTOMERS(ID),
    FOREIGN KEY (ISIN) REFERENCES INVESTMENT(ISIN)
);
