
-- Create a database

CREATE DATABASE IF NOT EXISTS SAMPLE_ASSET_MANAGEMENT;

USE SAMPLE_ASSET_MANAGEMENT;

CREATE TABLE IF NOT EXISTS SEGMENTS (
	SEG_ID VARCHAR(10) PRIMARY KEY,
    SEG_NAME VARCHAR(70)
);

CREATE TABLE IF NOT EXISTS SECURITY_REGION (
	SEC_REG_ID VARCHAR(10) PRIMARY KEY,
    REGION_NAME VARCHAR(70)
);

CREATE TABLE IF NOT EXISTS CUSTOMERS (
	ID VARCHAR(10) PRIMARY KEY,
    NAME VARCHAR(70),
    SEG_ID VARCHAR(10),
    TYPE CHAR(20),
    ADVISOR VARCHAR(75),
    TEAM_HEAD VARCHAR(75),
    SEGMENT_HEAD VARCHAR(75),
    REGION VARCHAR(30),
    FOREIGN KEY (SEG_ID) REFERENCES SEGMENTS (SEG_ID) 
);


CREATE TABLE IF NOT EXISTS EXCH_RATE (
	FROM_CCY CHAR(3) NOT NULL,
    TO_CCY CHAR(3) NOT NULL,
    RATE DECIMAL(19,9),
    PRIMARY KEY (FROM_CCY,TO_CCY)
);

CREATE TABLE IF NOT EXISTS INVESTMENT (
	ISIN VARCHAR(12) PRIMARY KEY,
    SECURITY_NAME VARCHAR(50),
    SEC_REG_ID VARCHAR(10),
    ASSET_TYPE VARCHAR(20),
    SUB_ASSET_TYPE VARCHAR(50),
    CCY_CODE CHAR(3),
    FOREIGN KEY (CCY_CODE) REFERENCES EXCH_RATE(FROM_CCY),
    FOREIGN KEY (SEC_REG_ID) REFERENCES SECURITY_REGION (SEC_REG_ID) 
);


CREATE TABLE IF NOT EXISTS HOLDINGS (
	MONTH CHAR(3),
	ID VARCHAR(10),
	ISIN VARCHAR(12),
    CCY_CODE CHAR(3),
	AMOUNT NUMERIC,
    FOREIGN KEY (ID) REFERENCES CUSTOMERS(ID),
    FOREIGN KEY (ISIN) REFERENCES INVESTMENT(ISIN),
    FOREIGN KEY (CCY_CODE) REFERENCES EXCH_RATE(FROM_CCY)
);
